[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://opag-builder-api.herokuapp.com"

[[redirects]]
  from = "/api/*"
  to = "https://opag-builder-api.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://opag-builder-api.herokuapp.com"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://opag-builder-api.herokuapp.com"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://opag-builder-api.herokuapp.com"